export const ADD_TO_CART = 'ADD_TO_CART';
export const REMOVE_FROM_CART = 'REMOVE_FROM_CART';
export const UPDATE_CART_ITEM = 'UPDATE_CART_ITEM';
export const REMOVE_STOCK_ITEM = 'REMOVE_STOCK_ITEM';
export const RECEIVE_PRODUCTS = 'RECEIVE_PRODUCTS';